# Modified from https://github.com/pmeier/light-the-torch
name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    

jobs:
  channel:
    strategy:
      matrix:
        os:
          - ubuntu-latest
#           - windows-latest
#           - macos-latest
        python-version:
#           - "3.7"
#           - "3.8"
#           - "3.9"
          - "3.10"
        pytorch-channel:
          - stable
#           - test
#           - nightly
#           - lts
#         exclude:
#           - os: macos-latest
#             pytorch-channel: lts
#           - python-version: "3.10"
#             pytorch-channel: lts
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup development environment
        uses: ./.github/actions/setup-dev-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Collect environment information
        run: python ./.github/scripts/collect_env.py

      - name: Install PyTorch distributions
        run:
          ltt install --pytorch-channel=${{ matrix.pytorch-channel }} torch torchvision
          torchaudio

      - name: Check if CPU only
        shell: python
        run: |
          import sys
          import torch
          cuda = torch.version.cuda
          print(f"cuda = {cuda}")
          hip = torch.version.hip
          print(f"hip = {hip}")
          sys.exit(cuda or hip)

      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Pytest coverage comment
        if: ${{ github.ref == 'refs/heads/main' }}
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          hide-comment: true
          pytest-coverage-path: ./data/pytest-coverage_4.txt

      - name: Update Readme with Coverage Html
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n\${{ steps.coverageComment.outputs.coverageHtml }}\n<!-- Pytest Coverage Comment:End -->' ./README.md

      - name: Commit & Push changes to Readme
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions-js/push@master
        with:
          message: Update coverage on Readme
          github_token: ${{ secrets.GITHUB_TOKEN }}