# Modified from https://github.com/pmeier/light-the-torch
name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    

jobs:
  channel:
    strategy:
      matrix:
        os:
          - ubuntu-latest
#           - windows-latest
#           - macos-latest
        python-version:
#           - "3.7"
#           - "3.8"
#           - "3.9"
          - "3.10"
        pytorch-channel:
          - stable
#           - test
#           - nightly
#           - lts
#         exclude:
#           - os: macos-latest
#             pytorch-channel: lts
#           - python-version: "3.10"
#             pytorch-channel: lts
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup development environment
        uses: ./.github/actions/setup-dev-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Collect environment information
        run: python ./.github/scripts/collect_env.py

      - name: Install PyTorch distributions
        run:
          ltt install --pytorch-channel=${{ matrix.pytorch-channel }} torch torchvision
          torchaudio

      # Requires too much time computation.
      # - name: Install robustbench
      #   run:
      #     pip install git+https://github.com/RobustBench/robustbench.git

      - name: Check if CPU only
        shell: python
        run: |
          import sys
          import torch
          cuda = torch.version.cuda
          print(f"cuda = {cuda}")
          hip = torch.version.hip
          print(f"hip = {hip}")
          sys.exit(cuda or hip)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run pytest
        run: |
          pip install pytest pytest-cov
          pytest --cov . --cov-report=xml

      - name: Upload coverage reports to Codecov
        run: |
          # Replace `linux` below with the appropriate OS
          # Options are `alpine`, `linux`, `macos`, `windows`
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}